### PR TITLE
Check for valid keys and update datastore

### LINKED ISSUE #194: error with user_id=0
I tried the current autoupdate service and the new client:
```
autoupdate_1        | 2021/04/15 13:30:52 Internal Error: getting keys: get all keys: create keys for keysbuilder: load needed keys: restrict data: checker for key organisation/1/committee_ids: check fqids: restrict for collection committee: checking committee/1/id: getting organisation level: getting data from datastore: getOrSet for keys `[user/0/organisation_management_level]`: fetching key: fetching missing keys: requiesting keys from datastore: datastore returned status 400 BAD REQUEST: {
autoupdate_1        |   "error": {
autoupdate_1        |     "msg": "The key 'user/0/organisation_management_level' is no fqid, fqfield or collectionkey", 
autoupdate_1        |     "type": 1, 
autoupdate_1        |     "type_verbose": "INVALID_FORMAT"
autoupdate_1        |   }
autoupdate_1        | }
```
It seems that this is the request (altough I'm not sure):
```
{"collection":"organisation","ids":[1],"fields":{"id":null,"committee_ids":{"type":"relation-list","collection":"committee","fields":{"name":null,"description":null,"id":null,"meeting_ids":{"type":"relation-list","collection":"meeting","fields":{"name":null,"start_time":null,"end_time":null,"user_ids":null,"location":null,"id":null}}}}}}
```
Not that I'm not logged in, which would explain the user id 0.

### PR DESCRIPTION
**Pull request by ostcar**
fixes #194

### CODE REVIEW

**Comment by ostcar** [comment]
@FinnStutzenstein Please check if this fixes #194

File: cmd/datastore/main.go [hunk 1]
```diff
@@ -98,3 +103,11 @@ func exampleHandler(w http.ResponseWriter, r *http.Request) {
 
 	json.NewEncoder(w).Encode(responceData)
 }
+
+func validKey(key string) bool {
```
Comment (FinnStutzenstein) [inline cmd/datastore/main.go:107]: Looks good, but this function is duplicated.

**Review by FinnStutzenstein — APPROVED** [review]

File: cmd/datastore/main.go (hunk 1 above)
Comment (ostcar) [reply cmd/datastore/main.go:107]: It's true. I have to rewrite the fake datastore to use the code in the test package.
